version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    env_file:
      - ./env/.env.prod
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
